#!/bin/sh
# Rebuilds the SPIR-V shaders and their Bend embedding, reproducibly.
# Requires glslc (shaderc) and spirv-val (SPIRV-Tools). Run from anywhere:
#   sh shaders/build.sh
set -eu
cd "$(dirname "$0")"

for stage in vert frag; do
  glslc --target-env=vulkan1.3 -O -o "prim.$stage.spv" "prim.$stage"
  spirv-val --target-env vulkan1.3 "prim.$stage.spv"
done

# Bend has no binary include, so the words are emitted as list literals.
words() {
  od -An -v -t u4 "$1" | tr -s ' \n' ' ' | sed 's/^ //; s/ $//; s/ /, /g' |
    fold -s -w 76 | sed 's/^/    /; s/ *$//'
}

{
  echo "import Base"
  echo
  echo "# Generated by shaders/build.sh from prim.vert and prim.frag."
  echo "# Do not edit by hand; edit the GLSL and rerun the script."
  echo
  echo "def prim_vert() -> List<&2, U32>:"
  echo "  ["
  words prim.vert.spv
  echo "  ]"
  echo
  echo "def prim_frag() -> List<&2, U32>:"
  echo "  ["
  words prim.frag.spv
  echo "  ]"
} > spirv.bend
echo "wrote shaders/spirv.bend"
